spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodDB
    name: testDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect